window.portfolio = {
  person: {
    name: "Bahar Yuksel",
    initials: "BY",
    role: "Builder, student, product-minded maker",
    location: "Istanbul / remote",
    email: "hello@baharyuksel.com",
    headline: "I make learning tools, AI experiments, and visual systems that feel alive.",
    intro:
      "A curated portfolio of software, art, writing, and experiments. Dark, vivid, interactive, and focused on the work.",
    now: "Currently building Schoolar, refining AI-assisted learning flows, and turning prototypes into stronger case studies.",
    about:
      "I like work that is practical but not flat: tools with good structure, clear writing, expressive visuals, and enough interaction to make ideas easier to feel. My projects usually connect education, software, AI, research, and creative direction.",
  },
  pages: [
    ["home", "Home", "index.html"],
    ["work", "Work", "work.html"],
    ["art", "Art", "art.html"],
    ["writing", "Writing", "writing.html"],
    ["about", "About", "about.html"],
    ["contact", "Contact", "contact.html"],
  ],
  links: [
    { label: "Email", href: "mailto:hello@baharyuksel.com", note: "Direct contact" },
    { label: "GitHub", href: "https://github.com/", note: "Code and experiments" },
    { label: "LinkedIn", href: "https://www.linkedin.com/", note: "Professional profile" },
    { label: "Iter Agent", href: "../iter-agent/public/index.html", note: "Interactive project" },
    { label: "Schoolar", href: "../schoolar/", note: "Flagship project" },
  ],
  stats: [
    ["Field", "AI + EdTech"],
    ["Archive", "12+ works"],
    ["Style", "Blue / Green / Purple / Black"],
    ["Mode", "Interactive studio"],
  ],
  projects: [
    {
      title: "Schoolar",
      type: "Education platform",
      category: "Education",
      year: "2026",
      href: "../schoolar/",
      color: "#4de2d0",
      summary: "A learning platform concept for classes, resources, schedules, safety, progress evidence, and AI support.",
      role: "Product thinking, learning flows, interface direction",
      result: "A larger system idea for making student support more coordinated and visible.",
      tags: ["EdTech", "AI", "Product"],
      featured: true,
    },
    {
      title: "Iter Agent",
      type: "Academic intelligence prototype",
      category: "AI",
      year: "2026",
      href: "../iter-agent/public/index.html",
      color: "#966dff",
      summary: "A prototype for route planning, roleplay review, evidence graphs, opportunity signals, and local memory.",
      role: "AI workflow design, dashboard UX, system modeling",
      result: "Shows how planning can become more inspectable instead of staying vague.",
      tags: ["Agent", "Planning", "Evidence"],
      featured: true,
    },
    {
      title: "SDG4 Education App",
      type: "Mobile prototype",
      category: "Mobile",
      year: "2026",
      href: "../web/index.html",
      color: "#64a8ff",
      summary: "A Flutter prototype for student needs, donors, activities, and matching flows.",
      role: "Mobile app structure, support workflow, UI components",
      result: "Explores how educational needs can be collected and matched with help.",
      tags: ["Flutter", "Social good", "UX"],
      featured: true,
    },
    {
      title: "DressUp App",
      type: "Creative web tool",
      category: "Creative",
      year: "2026",
      href: "../DressUp_App/index.html",
      color: "#ff75d8",
      summary: "A playful browser experiment for outfit composition, color, and quick creative interaction.",
      role: "Interaction design, browser UI, playful systems",
      result: "A small example of how simple tools can still feel tactile.",
      tags: ["Web", "Creative", "Play"],
    },
    {
      title: "Kriptoloji Melodisi",
      type: "Presentation",
      category: "Storytelling",
      year: "2026",
      href: "../kriptoloji_melodisi_deck/output/output.pptx",
      color: "#4de2d0",
      summary: "A deck blending cryptology, music, rhythm, and narrative explanation.",
      role: "Narrative, structure, presentation design",
      result: "Makes an abstract technical topic easier to remember.",
      tags: ["Deck", "Learning", "Story"],
    },
    {
      title: "Canasavar",
      type: "Game experiment",
      category: "Game",
      year: "2026",
      href: "../htdocs/canasavar/index.html",
      color: "#966dff",
      summary: "A compact web game focused on feedback, visual clarity, and responsive interaction.",
      role: "Game loop, interaction, visual polish",
      result: "Practice in shipping a small complete interactive experience.",
      tags: ["Game", "JavaScript", "Prototype"],
    },
  ],
  art: [
    {
      title: "Learning Signal",
      medium: "Interface artwork",
      year: "2026",
      palette: ["#64a8ff", "#4de2d0", "#966dff"],
      text: "A visual system for routes, progress, and learning momentum.",
      tags: ["Interface", "Education"],
    },
    {
      title: "Night Index",
      medium: "Digital poster",
      year: "2026",
      palette: ["#966dff", "#050611", "#4de2d0"],
      text: "A poster study for a personal archive: dark surface, bright signal.",
      tags: ["Poster", "Typography"],
    },
    {
      title: "Signal Garden",
      medium: "Creative coding sketch",
      year: "2026",
      palette: ["#4de2d0", "#17204a", "#966dff"],
      text: "Abstract forms that react like connected ideas.",
      tags: ["Creative code", "Motion"],
    },
    {
      title: "Orbit Field",
      medium: "Visual experiment",
      year: "2026",
      palette: ["#050611", "#64a8ff", "#ff75d8"],
      text: "A study in circular composition, interface depth, and luminous contrast.",
      tags: ["System", "Visual"],
    },
  ],
  posts: [
    {
      title: "A personal site should be a workshop, not a museum",
      category: "Portfolio",
      date: "2026-08-09",
      read: "3 min",
      excerpt: "The strongest portfolios show current questions, living systems, and the next version of the work.",
    },
    {
      title: "How I think about useful AI in education",
      category: "AI",
      date: "2026-08-09",
      read: "4 min",
      excerpt: "Useful learning AI should reduce friction, reveal patterns, and help students continue without hiding effort.",
    },
    {
      title: "Visual taste as a product decision",
      category: "Design",
      date: "2026-08-09",
      read: "4 min",
      excerpt: "Color, density, rhythm, and motion tell people what kind of work they are inside.",
    },
  ],
  skills: ["Product thinking", "Flutter", "JavaScript", "AI workflows", "Education technology", "Creative coding", "Writing", "Presentation design", "Research", "UX systems"],
};
