window.portfolio = {
  person: {
    name: "Bahar Yüksel",
    initials: "BY",
    role: "High School Innovator",
    location: "Istanbul, Türkiye",
    email: "baharyuksel0403@gmail.com",
    headline: "I build where code, design, and art meet.",
    intro:
      "I'm a high school student in Istanbul, Robert College. I make software, interfaces, and visual work, mostly tools that help people learn.",
    now: "Building Schoolar and Iter, exploring AI for learning, and turning experiments into things I can show.",
    available: "Open to opportunities & collaboration",
    story: [
      "I'm Bahar Yüksel, a high school student in Robert College. I've always wanted to understand how things work, and what they could be. That curiosity turned into the need for developing my own version: building software, designing interfaces, and making visual work, often all at the same time.",
      "My favorite work lives where code, design, and art overlap. I care about tools that are engineered to actually work, designed to be clear, and made with enough personality to feel human. Most of what I build points at one question: how do I leave my mark?",
      "I'm still early, still learning, still shipping, still figuring out where this goes. But I'd rather be brave and build real things now than wait. If you're looking for someone innovative, curious, self-directed, and genuinely excited to make things, you now know where to look for.",
    ],
    lookingFor: [
      "Internships, programs, and mentorship",
      "Collaborators on education and AI projects",
      "People who will push me to build better",
    ],
  },
  pages: [
    ["home", "Home", "index.html"],
    ["work", "Work", "work.html"],
    ["research", "Research", "research.html"],
    ["art", "Art", "art.html"],
    ["writing", "Blog", "writing.html"],
    ["about", "About", "about.html"],
    ["contact", "Contact", "contact.html"],
  ],
  links: [
    { label: "Email", href: "mailto:baharyuksel0403@gmail.com", note: "The fastest way to reach me" },
    { label: "GitHub", href: "https://github.com/springdev28", note: "Code and experiments" },
    { label: "LinkedIn", href: "https://www.linkedin.com/in/bahar-y%C3%BCksel-15030930b/", note: "Professional profile" },
    { label: "Schoolar", href: "https://lightgrey-oyster-122608.hostingersite.com/", note: "My flagship project" },
    { label: "Iter", href: "https://greenyellow-eagle-758815.hostingersite.com/", note: "An interactive prototype" },
  ],
  disciplines: [
    {
      key: "Code",
      color: "#64a8ff",
      text: "Software and prototypes, from mobile apps to AI-assisted tools. I like turning a messy idea into something that actually runs.",
    },
    {
      key: "Design",
      color: "#4de2d0",
      text: "Interfaces and systems that make complex things feel simple. Layout, color, motion, and the small details that make software make sense.",
    },
    {
      key: "Art",
      color: "#966dff",
      text: "Visual and creative-coding work, where I experiment without a brief, and where a lot of my design instincts come from.",
    },
  ],
  // Your homepage portrait. Leave src empty to show your initials in a
  // styled frame; set src to a photo file (a cut-out / transparent-background
  // photo looks best) to show your picture instead.
  focusPhoto: {
    src: "portrait.png?v=4",
    alt: "Bahar Yüksel",
  },
  research: [
    {
      title: "AI support for learning paths",
      area: "AI + Education",
      status: "Exploring",
      year: "2026",
      question: "How can AI help students plan without making the process feel automatic or shallow?",
      notes: ["route planning", "feedback loops", "student agency"],
      color: "#4de2d0",
    },
    {
      title: "Evidence-centered portfolios",
      area: "Product + UX",
      status: "Building",
      year: "2026",
      question: "What makes a project page feel credible quickly?",
      notes: ["case studies", "proof", "process"],
      color: "#64a8ff",
    },
    {
      title: "Visual interfaces for abstract ideas",
      area: "Design",
      status: "Collecting",
      year: "2026",
      question: "When do visuals make technical concepts easier to remember?",
      notes: ["diagramming", "motion", "storytelling"],
      color: "#966dff",
    },
  ],
  projects: [
    {
      title: "Schoolar",
      type: "Education platform",
      category: "Education",
      year: "2026",
      href: "../schoolar/",
      color: "#4de2d0",
      summary: "An education platform for classes, resources, schedules, safety, progress, and AI support.",
      why: "School life is scattered across a dozen apps and chats. I wanted one place that actually holds it together.",
      role: "Product thinking, learning flows, interface direction",
      result: "A coordinated system that makes student support visible, structured, and easier to act on.",
      tags: ["EdTech", "AI", "Product"],
      image: "Schoolar-logo.png",
      imageBg: "#4de2d0",
      imageScale: "97%",
      featured: true,
    },
    {
      title: "Iter",
      type: "Academic intelligence agent",
      category: "AI",
      year: "2026",
      href: "../iter-agent/public/index.html",
      color: "#966dff",
      summary: "An academic intelligence prototype for route planning, review, evidence, and memory.",
      why: "Planning your studies usually lives in your head or a messy note. I wanted to make it visible and inspectable.",
      role: "AI workflow design, dashboard UX, system modeling",
      result: "Turns vague academic planning into an inspectable, evidence-backed workflow.",
      tags: ["Agent", "Planning", "Evidence"],
      image: "iter-logo.png",
      imageBg: "#ffffff",
      featured: true,
    },
    {
      title: "E-Donation",
      type: "Mobile prototype",
      category: "Mobile",
      year: "2026",
      href: "../web/index.html",
      color: "#64a8ff",
      summary: "Technovation Girls 2026 Quarterfinalist. A Flutter prototype connecting student needs, donors, activities, and matching.",
      why: "A lot of students and institutions need support that never reaches them. This explores how to match needs with people who can help.",
      role: "Mobile architecture, support workflow, UI components",
      result: "Connects real educational needs with donors and volunteers through structured matching.",
      tags: ["Flutter", "Social good", "UX"],
      image: "E-Donation-logo.png",
      imageBg: "#ffffff",
      featured: true,
    },
    
  ],
  // Art is organized into named albums. Each album has a name, a short
  // description, and a list of pieces. Add an album by copying one block.
  artAlbums: [
    {
      name: "RC Makers MateROV Team",
      description: "Designs made for Robert College's robotics team.",
      pieces: [
        {
          title: "Carcharodon the Great White",
          medium: "Mascot design",
          year: "2026",
          palette: ["#64a8ff", "#4de2d0", "#966dff"],
          text: "A full-body drawing of our mascot Carchorodon the Great White. With the combination of a shark, lifeguard outwear, and robotic legs, the design comminucates the message: The apex predator is here, beware! Made to be a body-size cardboard cutout.",
          tags: ["Mascot", "Robotics"],
          image: "Carcharodon-cutout.png",
        },
        {
          title: "Team Clothing Design - Front",
          medium: "Merchandise design",
          year: "2025",
          palette: ["#64a8ff", "#4de2d0", "#966dff"],
          text: "The robotics team's t-shirt and sweatshirt back design, combining the mascot and mechanics.",
          tags: ["Graphic design", "Merchandise"],
          image: "Sweat.png",
          imageBg: "#ffffff"
        },
        {
          title: "Team Clothing Design - Back",
          medium: "Merchandise design",
          year: "2025",
          palette: ["#64a8ff", "#4de2d0", "#966dff"],
          text: "The robotics team's t-shirt and sweatshirt front design, focusing on the water aspect of the team.",
          tags: ["Graphic design", "Merchandise"],
          image: "Makers-logo1.png",
          imageBg: "#ffffff"
        },
        {
          title: "Team Logo",
          medium: "Logo design",
          year: "2026",
          palette: ["#64a8ff", "#4de2d0", "#966dff"],
          text: "The robotics team's logo design, featuring a more animalistic Carcharodon.",
          tags: ["Graphic design", "Merchandise"],
          image: "Makers-logo.png",
          imageBg: "#ffffff"
        },
        {
          title: "Team Sticker Design - 1",
          medium: "Sticker design",
          year: "2025",
          palette: ["#64a8ff", "#4de2d0", "#966dff"],
          text: "A sticker design for the team, slogan: The Apex Predators.",
          tags: ["Sticker", "Merchandise"],
          image: "Makers-sticker.png",
        },
        {
          title: "Team Sticker Design - 2",
          medium: "Sticker design",
          year: "2026",
          palette: ["#64a8ff", "#4de2d0", "#966dff"],
          text: "A sticker design for the team, featuring the confidently-smiling face of the mascot.",
          tags: ["Sticker", "Merchandise"],
          image: "Makers-sticker1.png",
        },
        {
          title: "Team Banner Design",
          medium: "Banner design",
          year: "2026",
          palette: ["#64a8ff", "#4de2d0", "#966dff"],
          text: "A banner for the team's social media pages, slogan: Beware of the apex predator lurking in the depths.",
          tags: ["Banner", "Social media"],
          image: "Makers-banner.png",
        },
      ],
    },
    {
      name: "Graphic Novels",
      description: "Short comics based on various stories.",
      pieces: [
        {
          title: "Ağrıdağı'nın Laneti (The Curse of Mt. Ararat)",
          medium: "Graphic novel",
          year: "2025",
          palette: ["#966dff", "#050611", "#4de2d0"],
          text: "Based on the book The Legend of Mt. Ararat by Yaşar Kemal. A brand new story.",
          tags: ["Comic", "Old tales"],
          images: ["Sayfa_1.png", "Sayfa_2.png", "Sayfa_3.png", "Sayfa_4.png", "Sayfa_5.png", "Son.png"],
        },
        {
          title: "The Unhappy Child",
          medium: "Graphic novel",
          year: "2026",
          palette: ["#966dff", "#050611", "#4de2d0"],
          text: "Based on the book The Atlas of Misty Continents by İhsan Oktay Anar. One of the short stories within the book illustrated.",
          tags: ["Comic", "Old tales"],
          images: ["sf1.png", "sf2.png", "sf3.png"],
        },
      ],
    },
    {
      name: "Magazine Illustrations",
      description: "Illustrations of stories and poems for various school magazines.",
      pieces: [
        {
          title: "Kalabalık (Crowded)",
          medium: "Story illustration",
          year: "2026",
          palette: ["#4de2d0", "#17204a", "#966dff"],
          text: "Abstract forms that react like connected ideas. Based on the short story by the same name.",
          tags: ["Illustration", "Abstract"],
          image: "MS1.png",
        },
        {
          title: "O Yoldan Geçtim (I Went That Way)",
          medium: "Poem illustration",
          year: "2026",
          palette: ["#4de2d0", "#17204a", "#966dff"],
          text: "Abstract forms that react like connected ideas. Based on the poem by the same name.",
          tags: ["Illustration", "Abstract"],
          image: "MS2.png",
        },
      ],
    },
    {
      name: "Character Concept Art",
      description: "Some characters I designed to be used later in stories and games.",
      pieces: [
        {
          title: "Nihilunus",
          medium: "Character concept",
          year: "2025",
          palette: ["#64a8ff", "#4de2d0", "#966dff"],
          text: "The main character of a 2D story-driven RPG game, currently being developed.",
          tags: ["Concept art", "Game"],
          image: "Nihilunus.png",
        },
      ],
    },
    {
      name: "Other Artwork",
      description: "Works mainly related to school clubs and organizations.",
      pieces: [
        {
          title: "Macbeth",
          medium: "Play illustration",
          year: "2026",
          palette: ["#966dff", "#050611", "#4de2d0"],
          text: "Artwork made for a project about Macbeth by William Shakespeare in English class.",
          tags: ["Illustration", "Poster"],
          image: "Macbeth 3.png",
        },
        {
          title: "SEC Logo",
          medium: "Logo design",
          year: "2026",
          palette: ["#966dff", "#050611", "#4de2d0"],
          text: "Logo made for Robert College's Social Entrepreneurship Club.",
          tags: ["Logo", "Graphic design"],
          image: "SEC-logo.png",
        },
        {
          title: "SEC Sticker",
          medium: "Sticker design",
          year: "2026",
          palette: ["#966dff", "#050611", "#4de2d0"],
          text: "Sticker made for RC SEC's Social Entrepreneurship Festival 2026, which was on February 14.",
          tags: ["Sticker", "Graphic design"],
          image: "SEC-val-logo.png",
        },
      ],
    },
  ],
  posts: [
    {
      title: "A personal site should be a workshop, not a museum",
      category: "Portfolio",
      date: "2026-08-09",
      read: "5 min",
      excerpt: "The strongest portfolios show current questions, living systems, and the next version of the work.",
      body: [
        "  When I started building this site, my first instinct was to make a museum. Clean white walls, a few finished pieces under glass, everything labeled and done. It took me embarrassingly long to admit that a museum was exactly the wrong shape for where I am right now.",
        "  A museum is for things that are finished. It says: here is the final version, please do not touch. But I am not finished, and honestly I hope I never feel finished. Almost everything I care about is still moving, still being rewritten, still one version away from what I actually want it to be. Freezing it behind glass would have been a small lie, and small lies about your work have a way of becoming the truth you live in.",
        "  So I decided to build a workshop instead. A workshop is a place where you can see the tools on the bench, the half-built thing in the corner, and the sketch taped to the wall that shows where it is all going. It is not messy for the sake of being messy. It is honest about the fact that work is a process, not a trophy.",
        "  In practice that changed what I put here. Instead of only showing polished screenshots, I tried to show the questions I am still chasing. Schoolar and Iter are not case studies I finished and walked away from, they are systems I am still inside of, still arguing with. I would rather tell you what I am trying to figure out than pretend I already have the answer.",
        "  The scary part is that a workshop shows your reach exceeding your grasp. If I tell you I am trying to make learning feel less scattered, you can measure exactly how far I still am from that. But I have come to think that gap is the most interesting thing about anyone. A finished museum piece tells you what a person could do once. A workshop tells you what they are becoming.",
        "  There is a practical reason too. The people I want to reach, the ones who might hand me a chance, a program, a place on a team, are not really choosing the finished thing. They are betting on the next ten versions of me. The only honest way to show a trajectory is to show the work in motion, including the parts that are still rough and a little wrong.",
        "  So if you are reading this, treat the site like a workshop. Open the drawers. The projects are real but unfinished, the writing is me thinking out loud, and the art is where a lot of my instincts get tested long before they ever reach code. Come back in a few months and it should look different. If it does not, something has gone wrong.",
      ],
    },
    {
      title: "How I think about useful AI in education",
      category: "AI",
      date: "2026-08-09",
      read: "6 min",
      excerpt: "Useful learning AI should reduce friction, reveal patterns, and help students continue without hiding effort.",
      body: [
        "  Every few weeks someone announces that AI is about to change education forever. I want it to be true, because I am a student and I feel the friction every single day. But most of the demos I see are quietly solving the wrong problem. They do the student's work for them and call it help.",
        "  My honest rule is simple: AI in learning should reduce friction, not remove the effort that actually teaches you. There is a real difference between the two. Friction is the twenty minutes you waste figuring out which chapter to read, or the fact that your schedule, your resources, your feedback, and your deadlines all live in five different apps. Effort is the part where you struggle with the idea itself. The first one is worth deleting. The second one is the whole point of learning, and a tool that removes it is stealing from you while smiling.",
        "  The second thing I care about is that good learning AI should reveal patterns you cannot see on your own. It is hard to notice that you always lose momentum in the third week of a project, or that you understand something better when you draw it than when you read it. A tool that quietly surfaces that, and then steps back, is doing something genuinely useful instead of just impressive.",
        "  This is most of what I am trying to build into Iter. I did not want an agent that hands you an answer and hides its reasoning. I wanted planning you can inspect, where the evidence is visible and you are allowed to argue with it. If a system tells you what to do next, you should be able to see why, and disagree out loud. A black box that is usually right still teaches you the worst possible lesson, which is to stop thinking.",
        "  Schoolar comes from a different angle but the same belief. School life is scattered across a dozen apps and group chats, and that scattering quietly taxes the attention that should go to actual learning. So the goal there is not to be clever, it is to hold the pieces together, classes, resources, schedules, progress, support, in one place that makes the next step obvious. Coordination is unglamorous, but for a real student it is often the thing that is actually broken.",
        "  There are things I try hard not to build. I do not want tools that do your thinking and let you believe you understand. I do not want to hide effort in a way that feels great today and leaves you hollow at the exam, or worse, in the real moment you needed to know the thing and no tool was there. If a feature makes a student more dependent and less capable, it is a bad feature, no matter how good the launch video looks.",
        "  I want to be honest about my limits. I am a high school student building for students, which means I get some things right precisely because I am close to the problem, and I will get some things wrong for exactly the same reason. But I would rather build inside that gap than wait for permission to care. The friction is real, I am living in it, and that is a very good place to start.",
      ],
    },
    {
      title: "Visual taste as a product decision",
      category: "Design",
      date: "2026-08-09",
      read: "5 min",
      excerpt: "Color, density, rhythm, and motion tell people what kind of work they are inside.",
      body: [
        "  A lot of people treat visual design as decoration, the coat of paint you add at the end once the real work is done. I have slowly come to believe the opposite. Visual taste is a product decision, maybe one of the most important ones, because it tells people what kind of thing they are inside before they read a single word.",
        "  Think about how fast you judge a room. Color, density, rhythm, the amount of space between things, whether anything moves. You know within a second whether a place is serious or playful, careful or careless, made for you or made for someone else. Interfaces work exactly the same way. Every one of those choices is quietly telling the person what to expect and how much to trust what they are looking at.",
        "  I did not arrive at this through design theory. I arrived through art. Before I was building interfaces I was drawing, illustrating stories and poems for school magazines, designing a mascot for our robotics team, making stickers and posters and short comics. Art is where I learned that a tiny choice, a color that is slightly too warm, a line that is slightly too thick, can change the entire feeling of a thing. Design is just that instinct pointed at something people actually have to use.",
        "  So when I build, I treat the look as part of the argument, not a layer on top of it. If I am making a tool that is supposed to feel trustworthy, it cannot be loud and chaotic, no matter how many features it has. If I am making something that should feel alive and human, it cannot be so clean that it feels like a form at a government office. The visual language has to agree with the promise, or people feel the lie even when they cannot name it.",
        "  The comforting thing about taste is that it is not magic and you are not born with it. It is built out of thousands of small looks: paying attention to why one poster stops you and another slides past, and slowly stealing the reasons. Every piece of art I make sharpens the eye I bring to the next interface. They were never separate skills. They are the same skill wearing different clothes.",
        "  Where this matters most to me is learning tools, because those have to hold attention without shouting for it. A study tool that is visually exhausting will lose to one that is calm, even if the exhausting one technically does more. Clarity is not the absence of personality, it is personality with discipline. I want my work to feel expressive when that genuinely helps a student, and quiet when quiet is the kindest thing I can offer.",
        "  None of this means design comes last, or that it comes first. It means it runs through the whole thing. The engineering makes it work, the design makes it make sense, and the taste, the part that is hardest to explain, is what makes someone feel like a real person made this for them. That feeling is not decoration. For me it is most of the point.",
      ],
    },
  ],
  skillGroups: [
    { group: "Code", items: ["Python", "HTML", "CSS", "JavaScript", "TypeScript", "SQL", "Flutter", "AI workflows", "Web development", "Prototyping"] },
    { group: "Design", items: ["UI/UX systems", "Interaction design", "Visual systems", "Presentation design"] },
    { group: "Art & craft", items: ["Drawing", "Creative coding", "Writing", "Research", "Storytelling"] },
  ],
  approach: [
    {
      title: "Start from the question",
      text: "Every project begins with a real problem worth solving, not a feature to demo.",
    },
    {
      title: "Build to learn",
      text: "Working prototypes teach me more than plans do. I ship early and let the thing show me what's next.",
    },
    {
      title: "Design for clarity",
      text: "Interfaces should make complex ideas legible, expressive when it helps, quiet when it should be.",
    },
  ],
};
