window.portfolio = {
  person: {
    name: "Bahar Yuksel",
    initials: "BY",
    role: "AI & product builder — education systems",
    location: "Istanbul / remote",
    email: "hello@baharyuksel.com",
    headline: "Building AI tools that make learning work.",
    intro: "Product engineer and designer working across AI, education, and interface systems — from first prototype to shipped experience.",
    now: "Building Schoolar, designing AI learning flows, and turning experiments into documented case studies.",
    about:
      "I build across education, software, AI, and design — taking ideas from a research question to a working product. I care about systems that are legible, expressive, and genuinely useful, not just demos.",
    available: "Available for new projects",
  },
  pages: [
    ["home", "Home", "index.html"],
    ["work", "Work", "work.html"],
    ["research", "Research", "research.html"],
    ["art", "Art", "art.html"],
    ["writing", "Writing", "writing.html"],
    ["about", "About", "about.html"],
    ["contact", "Contact", "contact.html"],
  ],
  links: [
    { label: "Email", href: "mailto:hello@baharyuksel.com", note: "Direct contact" },
    { label: "GitHub", href: "https://github.com/", note: "Code and experiments" },
    { label: "LinkedIn", href: "https://www.linkedin.com/", note: "Professional profile" },
    { label: "Iter Agent", href: "../iter-agent/public/index.html", note: "Interactive project" },
    { label: "Schoolar", href: "../schoolar/", note: "Flagship project" },
  ],
  stats: [
    ["Focus", "AI · Education"],
    ["Building", "Schoolar"],
    ["Shipped", "6+ projects"],
    ["Based in", "Istanbul"],
  ],
  focusNodes: [
    { label: "AI", href: "work.html", angle: 225 },
    { label: "Schoolar", href: "work.html", angle: 315 },
    { label: "Art", href: "art.html", angle: 45 },
    { label: "Writing", href: "writing.html", angle: 135 },
  ],
  focusPhoto: {
    src: "",
    alt: "Bahar Yuksel",
  },
  research: [
    {
      title: "AI support for learning paths",
      area: "AI + Education",
      status: "Exploring",
      year: "2026",
      question: "How can AI help students plan without making the process feel automatic or shallow?",
      notes: ["route planning", "feedback loops", "student agency"],
      color: "#4de2d0",
    },
    {
      title: "Evidence-centered portfolios",
      area: "Product + UX",
      status: "Building",
      year: "2026",
      question: "What makes a project page feel credible quickly?",
      notes: ["case studies", "proof", "process"],
      color: "#64a8ff",
    },
    {
      title: "Visual interfaces for abstract ideas",
      area: "Design",
      status: "Collecting",
      year: "2026",
      question: "When do visuals make technical concepts easier to remember?",
      notes: ["diagramming", "motion", "storytelling"],
      color: "#966dff",
    },
  ],
  projects: [
    {
      title: "Schoolar",
      type: "Education platform",
      category: "Education",
      year: "2026",
      href: "../schoolar/",
      color: "#4de2d0",
      summary: "Education platform for classes, resources, schedules, safety, progress, and AI support.",
      role: "Product strategy, learning flows, interface direction",
      result: "A coordinated system that makes student support visible, structured, and easier to act on.",
      tags: ["EdTech", "AI", "Product"],
      featured: true,
    },
    {
      title: "Iter Agent",
      type: "Academic intelligence prototype",
      category: "AI",
      year: "2026",
      href: "../iter-agent/public/index.html",
      color: "#966dff",
      summary: "Academic intelligence prototype for route planning, review, evidence, and memory.",
      role: "AI workflow design, dashboard UX, system modeling",
      result: "Turns vague academic planning into an inspectable, evidence-backed workflow.",
      tags: ["Agent", "Planning", "Evidence"],
      featured: true,
    },
    {
      title: "SDG4 Education App",
      type: "Mobile prototype",
      category: "Mobile",
      year: "2026",
      href: "../web/index.html",
      color: "#64a8ff",
      summary: "Flutter prototype for student needs, donors, activities, and matching.",
      role: "Mobile architecture, support workflow, UI components",
      result: "Connects real educational needs with donors and volunteers through structured matching.",
      tags: ["Flutter", "Social good", "UX"],
      featured: true,
    },
    {
      title: "DressUp App",
      type: "Creative web tool",
      category: "Creative",
      year: "2026",
      href: "../DressUp_App/index.html",
      color: "#ff75d8",
      summary: "Browser experiment for outfit composition, color, and quick interaction.",
      role: "Interaction design, browser UI, playful systems",
      result: "Shows how a lightweight tool can still feel tactile and responsive.",
      tags: ["Web", "Creative", "Play"],
    },
    {
      title: "Kriptoloji Melodisi",
      type: "Presentation",
      category: "Storytelling",
      year: "2026",
      href: "../kriptoloji_melodisi_deck/output/output.pptx",
      color: "#4de2d0",
      summary: "Deck blending cryptology, music, rhythm, and narrative.",
      role: "Narrative, structure, presentation design",
      result: "Turns an abstract technical topic into a memorable, teachable narrative.",
      tags: ["Deck", "Learning", "Story"],
    },
    {
      title: "Canasavar",
      type: "Game experiment",
      category: "Game",
      year: "2026",
      href: "../htdocs/canasavar/index.html",
      color: "#966dff",
      summary: "Compact web game focused on feedback, clarity, and interaction.",
      role: "Game loop, interaction, visual polish",
      result: "A complete, shipped interactive experience built from the ground up.",
      tags: ["Game", "JavaScript", "Prototype"],
    },
  ],
  art: [
    {
      title: "Learning Signal",
      medium: "Interface artwork",
      year: "2026",
      palette: ["#64a8ff", "#4de2d0", "#966dff"],
      text: "A visual system for routes, progress, and learning momentum.",
      tags: ["Interface", "Education"],
    },
    {
      title: "Night Index",
      medium: "Digital poster",
      year: "2026",
      palette: ["#966dff", "#050611", "#4de2d0"],
      text: "A poster study for a personal archive: dark surface, bright signal.",
      tags: ["Poster", "Typography"],
    },
    {
      title: "Signal Garden",
      medium: "Creative coding sketch",
      year: "2026",
      palette: ["#4de2d0", "#17204a", "#966dff"],
      text: "Abstract forms that react like connected ideas.",
      tags: ["Creative code", "Motion"],
    },
    {
      title: "Orbit Field",
      medium: "Visual experiment",
      year: "2026",
      palette: ["#050611", "#64a8ff", "#ff75d8"],
      text: "A study in circular composition, interface depth, and luminous contrast.",
      tags: ["System", "Visual"],
    },
  ],
  posts: [
    {
      title: "A personal site should be a workshop, not a museum",
      category: "Portfolio",
      date: "2026-08-09",
      read: "3 min",
      excerpt: "The strongest portfolios show current questions, living systems, and the next version of the work.",
    },
    {
      title: "How I think about useful AI in education",
      category: "AI",
      date: "2026-08-09",
      read: "4 min",
      excerpt: "Useful learning AI should reduce friction, reveal patterns, and help students continue without hiding effort.",
    },
    {
      title: "Visual taste as a product decision",
      category: "Design",
      date: "2026-08-09",
      read: "4 min",
      excerpt: "Color, density, rhythm, and motion tell people what kind of work they are inside.",
    },
  ],
  skills: ["Product thinking", "AI workflows", "Flutter", "JavaScript", "Education technology", "UX systems", "Creative coding", "Research", "Writing", "Presentation design"],
  approach: [
    {
      title: "Start from the question",
      text: "Every project begins with a real problem worth solving, not a feature to demo.",
    },
    {
      title: "Build to learn",
      text: "Working prototypes reveal more than specs. I ship early and let the system teach me.",
    },
    {
      title: "Design for clarity",
      text: "Interfaces should make complex ideas legible — expressive when it helps, quiet when it should be.",
    },
  ],
};
